# Generated by Django 4.2.2 on 2023-08-04 07:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_url_fields_add_sorted_many2many_skills'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], help_text='The vote choice (Up or Down).', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='projects/default.jpg', help_text='The featured image of the project.', null=True, upload_to='projects/'),
        ),
        AlterSortedManyToManyField(
            model_name='project',
            name='skills',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='The relevant skills in the project.', related_name='Project', to='authentication.skill'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
