# Generated by Django 4.2.2 on 2023-08-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drop_vote_tabel_add_vote_field_in_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Combination of id and title as a lookup field.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project that is being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.project'),
        ),
    ]
