# Generated by Django 4.2.2 on 2023-07-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the skill.', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='A description of the skill.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A detailed bio of the user about himself.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='A profile picture of the user.', null=True, upload_to='')),
                ('github', models.CharField(blank=True, help_text='The GitHub profile link.', max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='The LinkedIn profile link.', max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, help_text='The YouTube profile link.', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='The gender of the user.', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='The date of birth of the user.', null=True)),
                ('skills', models.ManyToManyField(blank=True, help_text='The skills associated with the profile.', null=True, related_name='profile', to='authentication.skill')),
                ('user', models.OneToOneField(blank=True, help_text='The related user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
