# Generated by Django 4.2.2 on 2023-08-04 07:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank=True, help_text='A short intro or a post title.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='skill',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A detailed bio of the user about themselves.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/user-default.png', help_text='A profile picture of the user.', null=True, upload_to='profiles/'),
        ),
        AlterSortedManyToManyField(
            model_name='profile',
            name='skills',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='The skills associated with the profile.', related_name='profile', to='authentication.skill'),
        ),
    ]
