# Generated by Django 4.2.2 on 2023-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_url_fields_add_sorted_many2many_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Combination of id and name as a lookup field.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Combination of id and name as a lookup field.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the skill.', max_length=200, null=True, unique=True),
        ),
    ]
